-- ============================================================
-- MOEEN
-- Multi-user Job Application Tracking Schema
-- PostgreSQL
-- ============================================================


-- ============================================================
-- ENUM TYPES
-- ============================================================

CREATE TYPE company_size AS ENUM (
    'STARTUP',
    'SMALL',
    'MEDIUM',
    'LARGE',
    'ENTERPRISE'
);


CREATE TYPE work_arrangement AS ENUM (
    'ONSITE',
    'REMOTE',
    'HYBRID'
);


CREATE TYPE employment_type AS ENUM (
    'FULL_TIME',
    'PART_TIME',
    'INTERNSHIP',
    'CONTRACT',
    'FREELANCE',
    'TEMPORARY'
);


CREATE TYPE experience_level AS ENUM (
    'INTERNSHIP',
    'ENTRY_LEVEL',
    'JUNIOR',
    'MID_LEVEL',
    'SENIOR',
    'LEAD',
    'MANAGER',
    'EXECUTIVE'
);


CREATE TYPE salary_currency AS ENUM (
    'USD',
    'EUR',
    'GBP',
    'EGP',
    'SAR',
    'AED',
    'CAD',
    'AUD'
);


CREATE TYPE application_status AS ENUM (
    'PREPARING',
    'APPLIED',
    'UNDER_REVIEW',
    'ASSESSMENT',
    'PHONE_SCREEN',
    'INTERVIEW',
    'FINAL_INTERVIEW',
    'OFFER',
    'ACCEPTED',
    'REJECTED',
    'WITHDRAWN',
    'GHOSTED',
    'ARCHIVED'
);


CREATE TYPE application_priority AS ENUM (
    'LOW',
    'MEDIUM',
    'HIGH'
);


CREATE TYPE interview_type AS ENUM (
    'RECRUITER_CALL',
    'HR_INTERVIEW',
    'TECHNICAL_INTERVIEW',
    'LIVE_CODING',
    'SYSTEM_DESIGN',
    'BEHAVIORAL',
    'HIRING_MANAGER',
    'FINAL_INTERVIEW'
);


CREATE TYPE interview_result AS ENUM (
    'SCHEDULED',
    'COMPLETED',
    'PASSED',
    'FAILED',
    'CANCELLED'
);


CREATE TYPE reminder_status AS ENUM (
    'PENDING',
    'COMPLETED',
    'CANCELLED'
);


CREATE TYPE contact_type AS ENUM (
    'RECRUITER',
    'HIRING_MANAGER',
    'INTERVIEWER',
    'HR',
    'EMPLOYEE',
    'REFERRAL',
    'OTHER'
);


CREATE TYPE document_type AS ENUM (
    'RESUME',
    'COVER_LETTER',
    'PORTFOLIO',
    'CERTIFICATE',
    'ASSESSMENT',
    'OFFER_LETTER',
    'OTHER'
);


-- ============================================================
-- USERS
-- ============================================================

CREATE TABLE users (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,

    email VARCHAR(255) NOT NULL,

    password_hash VARCHAR(255) NOT NULL,

    enabled BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_users
        PRIMARY KEY (id)
);


-- Case-insensitive email uniqueness.
CREATE UNIQUE INDEX ux_users_email_lower
    ON users (LOWER(email));


-- ============================================================
-- COMPANIES
-- ============================================================

CREATE TABLE companies (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    user_id BIGINT NOT NULL,

    name VARCHAR(255) NOT NULL,

    website VARCHAR(500),
    linkedin_url VARCHAR(500),

    industry VARCHAR(150),

    company_size company_size,

    headquarters VARCHAR(255),

    description TEXT,

    rating SMALLINT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_companies
        PRIMARY KEY (id),

    CONSTRAINT fk_companies_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_companies_rating
        CHECK (
            rating IS NULL
            OR rating BETWEEN 1 AND 5
        ),

    -- Required later for composite ownership foreign keys.
    CONSTRAINT uq_companies_id_user
        UNIQUE (id, user_id)
);


-- Different users may both save "Google".
-- Prevent duplicate company names only inside the same account.
CREATE UNIQUE INDEX ux_companies_user_name
    ON companies (user_id, LOWER(name));


CREATE INDEX ix_companies_user
    ON companies (user_id);


-- ============================================================
-- JOB OPPORTUNITIES
-- ============================================================

CREATE TABLE job_opportunities (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    user_id BIGINT NOT NULL,

    company_id BIGINT NOT NULL,

    title VARCHAR(255) NOT NULL,

    description TEXT,

    job_url VARCHAR(1000),

    source VARCHAR(100),

    location VARCHAR(255),

    work_arrangement work_arrangement,

    employment_type employment_type,

    experience_level experience_level,

    minimum_salary NUMERIC(12, 2),

    maximum_salary NUMERIC(12, 2),

    salary_currency salary_currency,

    posting_date DATE,

    application_deadline DATE,

    active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_job_opportunities
        PRIMARY KEY (id),

    CONSTRAINT fk_job_opportunities_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE RESTRICT,

    /*
     * Important:
     * This guarantees that company_id belongs to the SAME user.
     *
     * User 2 cannot create a job using User 1's company.
     */
    CONSTRAINT fk_job_opportunities_company_owner
        FOREIGN KEY (company_id, user_id)
        REFERENCES companies(id, user_id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_job_opportunities_min_salary
        CHECK (
            minimum_salary IS NULL
            OR minimum_salary >= 0
        ),

    CONSTRAINT ck_job_opportunities_max_salary
        CHECK (
            maximum_salary IS NULL
            OR maximum_salary >= 0
        ),

    CONSTRAINT ck_job_opportunities_salary_range
        CHECK (
            minimum_salary IS NULL
            OR maximum_salary IS NULL
            OR maximum_salary >= minimum_salary
        ),

    /*
     * If any salary value exists,
     * currency must also exist.
     */
    CONSTRAINT ck_job_opportunities_salary_currency
        CHECK (
            salary_currency IS NOT NULL
            OR (
                minimum_salary IS NULL
                AND maximum_salary IS NULL
            )
        ),

    CONSTRAINT ck_job_opportunities_dates
        CHECK (
            posting_date IS NULL
            OR application_deadline IS NULL
            OR application_deadline >= posting_date
        ),

    CONSTRAINT uq_job_opportunities_id_user
        UNIQUE (id, user_id)
);


CREATE INDEX ix_job_opportunities_user
    ON job_opportunities (user_id);


CREATE INDEX ix_job_opportunities_company
    ON job_opportunities (company_id);


CREATE INDEX ix_job_opportunities_user_company
    ON job_opportunities (user_id, company_id);


CREATE INDEX ix_job_opportunities_user_created_at
    ON job_opportunities (user_id, created_at DESC);


-- ============================================================
-- JOB APPLICATIONS
-- ============================================================

CREATE TABLE job_applications (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    user_id BIGINT NOT NULL,

    job_opportunity_id BIGINT NOT NULL,

    current_status application_status NOT NULL,

    priority application_priority NOT NULL DEFAULT 'MEDIUM',

    applied_at TIMESTAMPTZ,

    follow_up_at TIMESTAMPTZ,

    expected_salary NUMERIC(12, 2),

    notes TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_job_applications
        PRIMARY KEY (id),

    CONSTRAINT fk_job_applications_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE RESTRICT,

    /*
     * Guarantees that the application can only use a
     * job opportunity owned by the same user.
     */
    CONSTRAINT fk_job_applications_job_owner
        FOREIGN KEY (job_opportunity_id, user_id)
        REFERENCES job_opportunities(id, user_id)
        ON DELETE RESTRICT,

    /*
     * One job opportunity can have at most one application.
     */
    CONSTRAINT uq_job_applications_job
        UNIQUE (job_opportunity_id),

    CONSTRAINT ck_job_applications_expected_salary
        CHECK (
            expected_salary IS NULL
            OR expected_salary >= 0
        ),

    CONSTRAINT ck_job_applications_follow_up
        CHECK (
            applied_at IS NULL
            OR follow_up_at IS NULL
            OR follow_up_at >= applied_at
        ),

    /*
     * PREPARING can exist before submission.
     *
     * Any later application state should have an applied_at.
     */
    CONSTRAINT ck_job_applications_applied_at
        CHECK (
            current_status = 'PREPARING'
            OR applied_at IS NOT NULL
        ),

    CONSTRAINT uq_job_applications_id_user
        UNIQUE (id, user_id)
);


CREATE INDEX ix_job_applications_user
    ON job_applications (user_id);


CREATE INDEX ix_job_applications_user_status
    ON job_applications (user_id, current_status);


CREATE INDEX ix_job_applications_user_applied_at
    ON job_applications (user_id, applied_at DESC);


CREATE INDEX ix_job_applications_user_follow_up
    ON job_applications (user_id, follow_up_at);


CREATE INDEX ix_job_applications_user_updated_at
    ON job_applications (user_id, updated_at DESC);


-- ============================================================
-- APPLICATION STATUS HISTORY
-- ============================================================

CREATE TABLE application_status_history (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    application_id BIGINT NOT NULL,

    previous_status application_status,

    new_status application_status NOT NULL,

    comment TEXT,

    changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_application_status_history
        PRIMARY KEY (id),

    CONSTRAINT fk_application_status_history_application
        FOREIGN KEY (application_id)
        REFERENCES job_applications(id)
        ON DELETE CASCADE,

    CONSTRAINT ck_application_status_history_change
        CHECK (
            previous_status IS NULL
            OR previous_status <> new_status
        )
);


CREATE INDEX ix_application_status_history_application_changed
    ON application_status_history (
        application_id,
        changed_at DESC
    );


-- ============================================================
-- INTERVIEWS
-- ============================================================

CREATE TABLE interviews (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    application_id BIGINT NOT NULL,

    interview_type interview_type NOT NULL,

    interview_stage VARCHAR(100),

    scheduled_at TIMESTAMPTZ NOT NULL,

    duration_minutes INTEGER,

    location VARCHAR(500),

    meeting_url VARCHAR(1000),

    interviewer_name VARCHAR(255),

    interviewer_email VARCHAR(255),

    preparation_notes TEXT,

    feedback TEXT,

    result interview_result NOT NULL DEFAULT 'SCHEDULED',

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_interviews
        PRIMARY KEY (id),

    CONSTRAINT fk_interviews_application
        FOREIGN KEY (application_id)
        REFERENCES job_applications(id)
        ON DELETE CASCADE,

    CONSTRAINT ck_interviews_duration
        CHECK (
            duration_minutes IS NULL
            OR duration_minutes > 0
        )
);


CREATE INDEX ix_interviews_application
    ON interviews (application_id);


CREATE INDEX ix_interviews_application_scheduled
    ON interviews (application_id, scheduled_at);


CREATE INDEX ix_interviews_scheduled
    ON interviews (scheduled_at);


-- ============================================================
-- REMINDERS
-- ============================================================

CREATE TABLE reminders (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    application_id BIGINT NOT NULL,

    title VARCHAR(255) NOT NULL,

    description TEXT,

    reminder_at TIMESTAMPTZ NOT NULL,

    status reminder_status NOT NULL DEFAULT 'PENDING',

    completed_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_reminders
        PRIMARY KEY (id),

    CONSTRAINT fk_reminders_application
        FOREIGN KEY (application_id)
        REFERENCES job_applications(id)
        ON DELETE CASCADE,

    /*
     * COMPLETED -> completed_at must exist.
     * Other states -> completed_at must be NULL.
     */
    CONSTRAINT ck_reminders_completed_at
        CHECK (
            (
                status = 'COMPLETED'
                AND completed_at IS NOT NULL
            )
            OR
            (
                status <> 'COMPLETED'
                AND completed_at IS NULL
            )
        )
);


CREATE INDEX ix_reminders_application
    ON reminders (application_id);


CREATE INDEX ix_reminders_application_time
    ON reminders (application_id, reminder_at);


CREATE INDEX ix_reminders_status_time
    ON reminders (status, reminder_at);


-- ============================================================
-- CONTACTS
-- ============================================================

CREATE TABLE contacts (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    user_id BIGINT NOT NULL,

    company_id BIGINT,

    full_name VARCHAR(255) NOT NULL,

    job_title VARCHAR(255),

    email VARCHAR(255),

    phone VARCHAR(50),

    linkedin_url VARCHAR(500),

    contact_type contact_type NOT NULL,

    notes TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_contacts
        PRIMARY KEY (id),

    CONSTRAINT fk_contacts_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE RESTRICT,

    /*
     * If company_id exists, it must belong to the
     * same user as this contact.
     */
    CONSTRAINT fk_contacts_company_owner
        FOREIGN KEY (company_id, user_id)
        REFERENCES companies(id, user_id)
        ON DELETE RESTRICT,

    CONSTRAINT uq_contacts_id_user
        UNIQUE (id, user_id)
);


CREATE INDEX ix_contacts_user
    ON contacts (user_id);


CREATE INDEX ix_contacts_company
    ON contacts (company_id);


CREATE INDEX ix_contacts_user_email
    ON contacts (user_id, email);


-- ============================================================
-- APPLICATION CONTACTS
-- ============================================================

CREATE TABLE application_contacts (

    application_id BIGINT NOT NULL,

    contact_id BIGINT NOT NULL,

    /*
     * user_id is intentionally stored here.
     *
     * This allows PostgreSQL to guarantee that both
     * application and contact belong to the same user.
     */
    user_id BIGINT NOT NULL,

    CONSTRAINT pk_application_contacts
        PRIMARY KEY (application_id, contact_id),

    CONSTRAINT fk_application_contacts_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_application_contacts_application_owner
        FOREIGN KEY (application_id, user_id)
        REFERENCES job_applications(id, user_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_application_contacts_contact_owner
        FOREIGN KEY (contact_id, user_id)
        REFERENCES contacts(id, user_id)
        ON DELETE CASCADE
);


CREATE INDEX ix_application_contacts_user
    ON application_contacts (user_id);


CREATE INDEX ix_application_contacts_contact
    ON application_contacts (contact_id);


-- ============================================================
-- DOCUMENTS
-- ============================================================

CREATE TABLE documents (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    application_id BIGINT NOT NULL,

    original_filename VARCHAR(255) NOT NULL,

    stored_filename VARCHAR(255) NOT NULL,

    content_type VARCHAR(150) NOT NULL,

    file_size BIGINT NOT NULL,

    storage_path VARCHAR(1000) NOT NULL,

    document_type document_type NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_documents
        PRIMARY KEY (id),

    CONSTRAINT fk_documents_application
        FOREIGN KEY (application_id)
        REFERENCES job_applications(id)
        ON DELETE CASCADE,

    CONSTRAINT ck_documents_file_size
        CHECK (file_size > 0)
);


CREATE INDEX ix_documents_application
    ON documents (application_id);


CREATE INDEX ix_documents_application_type
    ON documents (application_id, document_type);