-- Study time is scoped to a stable browser owner key until authentication is wired.
CREATE TABLE study_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    owner_key VARCHAR(64) NOT NULL,
    subject VARCHAR(120) NOT NULL,
    duration_minutes INTEGER NOT NULL,
    studied_on DATE NOT NULL,
    completed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    source VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(20) NOT NULL DEFAULT 'system',
    updated_by VARCHAR(20),

    CONSTRAINT pk_study_sessions PRIMARY KEY (id),
    CONSTRAINT ck_study_sessions_duration CHECK (duration_minutes BETWEEN 1 AND 1440),
    CONSTRAINT ck_study_sessions_source CHECK (source IN ('POMODORO', 'MANUAL'))
);

CREATE INDEX ix_study_sessions_owner_date
    ON study_sessions (owner_key, studied_on DESC);

CREATE TABLE study_preferences (
    owner_key VARCHAR(64) NOT NULL,
    focus_minutes SMALLINT NOT NULL DEFAULT 25,
    short_break_minutes SMALLINT NOT NULL DEFAULT 5,
    long_break_minutes SMALLINT NOT NULL DEFAULT 15,
    sessions_until_long_break SMALLINT NOT NULL DEFAULT 4,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(20) NOT NULL DEFAULT 'system',
    updated_by VARCHAR(20),

    CONSTRAINT pk_study_preferences PRIMARY KEY (owner_key),
    CONSTRAINT ck_study_preferences_focus CHECK (focus_minutes BETWEEN 1 AND 180),
    CONSTRAINT ck_study_preferences_short_break CHECK (short_break_minutes BETWEEN 1 AND 60),
    CONSTRAINT ck_study_preferences_long_break CHECK (long_break_minutes BETWEEN 1 AND 90),
    CONSTRAINT ck_study_preferences_cycle CHECK (sessions_until_long_break BETWEEN 1 AND 12)
);
